# Generated by Django 5.1.2 on 2024-11-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('section', models.CharField(choices=[('INFO', 'Information'), ('RES', 'Resources'), ('EVT', 'Events'), ('OPP', 'Opportunities'), ('PROF', 'Profiles')], max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('source', models.CharField(max_length=42)),
                ('author', models.CharField(max_length=42)),
                ('website', models.URLField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('publicationdate', models.DateTimeField(verbose_name='Publication date')),
            ],
        ),
    ]
