# Generated by Django 5.1.5 on 2025-01-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='publicationdate',
        ),
    ]
