# Generated by Django 5.1.5 on 2025-01-28 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_new_publicationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='publicationdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date'),
            preserve_default=False,
        ),
    ]
