# Generated by Django 5.1.5 on 2025-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_new_publicationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='news'),
        ),
    ]
