# Generated by Django 5.1.5 on 2025-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_new_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
