# Generated by Django 5.1.5 on 2025-02-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_new_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='photo',
            field=models.ImageField(blank=True, default='img/news/default.jpg', null=True, upload_to='news'),
        ),
    ]
