# Generated by Django 5.1.5 on 2025-03-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_new_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='section',
            field=models.CharField(choices=[('INFORMATIONS', 'Information'), ('RESOURCES', 'Resources'), (' ÉVÉNEMENTS', 'Events'), (' OPPORTUNITÉS', 'Opportunities'), ('PROFILES', 'Profiles')], max_length=15),
        ),
    ]
