# Generated by Django 5.1.5 on 2025-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_new_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='section',
            field=models.CharField(choices=[('Informations', 'Information'), ('Ressources', 'Resources'), ('Evenements', 'Events'), ('Opportunites', 'Opportunities'), ('Profiles', 'Profiles')], max_length=15),
        ),
    ]
